import { REPORT_COST, GENERATE_MORE_COST, SIGNUP_GRANT } from '../../lib/credits';

export const HERO = {
  eyebrow: 'CSV → report · no SQL, no pivot tables',
  // headline rendered with an italic accent on "written summary"
  headlineA: 'Ten charts and a ',
  headlineEm: 'written summary',
  headlineB: ', from one spreadsheet.',
  sub: 'Upload a CSV or Excel file. ChartSage profiles the data, picks the ten charts that actually say something, and writes the analysis to match.',
  ctaPrimary: "Upload a CSV — first one's free",
  ctaSecondary: 'See an example ↓',
};

export const TRUST = [
  'Private to your account',
  'Not used to train AI models',
  'CSV & Excel',
  'Nothing to install, no SQL',
];

export const HOW = [
  { n: '01', h: 'Upload a file', p: 'Drop in a CSV or Excel export. No cleaning, no formatting rules, no column naming — it reads what you have.' },
  { n: '02', h: 'The AI reads it', p: 'It profiles every column, works out the types and relationships, and chooses the ten charts worth showing for this particular dataset.' },
  { n: '03', h: 'You get a report', p: 'Interactive charts, a written summary of what stands out, and a flag on anything that looks off in the data. Export to PDF or keep it in your account.' },
];

export const FEATURES = [
  { h: 'Ten charts, chosen for your data', p: 'Not a fixed template. The AI picks the chart types that fit your columns — distributions, trends, correlations, breakdowns.' },
  { h: 'A written summary', p: 'The headline findings in plain English, up top — so you can read the takeaway before you read the charts.' },
  { h: 'A data-quality flag', p: 'It tells you when something looks wrong — blank fields, odd outliers, mixed types — instead of quietly charting it anyway.' },
  { h: 'PDF export', p: 'One click to a clean PDF you can send as-is.' },
  { h: 'More charts on demand', p: "Want a different cut? Generate five more and they're added to the report." },
  { h: 'Saved to your account', p: 'Every report you make stays in one place. Come back to it, re-export it, or pick up where you left off.' },
];

export const USES = [
  { h: 'Sales', p: 'pipeline · revenue by region · win rates · order values' },
  { h: 'Marketing', p: 'campaign performance · channel mix · spend vs. conversion' },
  { h: 'Finance & ops', p: 'spend · headcount · throughput · month-over-month' },
  { h: 'Research', p: 'survey responses · breakdowns · correlations between fields' },
];

export const PRICING = {
  blurbH: 'Try it, then top up later.',
  blurbP: 'Reports and extra charts run on credits, so you only pay for what you make. Paid top-ups are coming soon — for now, the free report plus your starter credits are enough to put it through its paces.',
  rows: [
    { k: 'First report', v: 'Free · no account', muted: false },
    { k: 'New account starts with', v: `${SIGNUP_GRANT} credits`, muted: false },
    { k: 'A report', v: `${REPORT_COST} credits`, muted: false },
    { k: 'Five more charts', v: `${GENERATE_MORE_COST} credits`, muted: false },
    { k: 'Paid top-ups', v: 'Coming soon', muted: true },
  ],
};

export const FAQ = [
  { q: 'What files can I upload?', a: "CSV and Excel (.xlsx). Drop in an export from your database, CRM, analytics tool, or just a spreadsheet you've been keeping by hand." },
  { q: 'What happens to my data?', a: "Your file is stored privately and used only to build your report. It's tied to your account, isn't shared, and isn't used to train AI models. We don't sell it and we don't look at it." },
  { q: 'How accurate are the charts?', a: "The charts are drawn from your actual numbers — they're your numbers, plotted. The written summary is generated by AI reading those numbers: usually sharp, occasionally worth a second look. Treat it as a fast first pass, not the final word." },
  { q: 'How do credits work?', a: `Your first report is free with no account. A new account starts with ${SIGNUP_GRANT} credits; a report costs ${REPORT_COST} and generating five more charts costs ${GENERATE_MORE_COST}. Paid top-ups are on the way.` },
  { q: 'Do I need to know SQL or set anything up?', a: "No. There's nothing to install and no query to write. Upload a file in the browser and you have a report." },
  { q: 'Can I share or export it?', a: 'Every report exports to a clean PDF. Saved reports stay in your account so you can come back and re-export any time.' },
];

export const CLOSING = {
  h: 'Stop screenshotting spreadsheets.',
  p: "Upload one file and see what's in it. The first report is on us.",
  cta: 'Upload a CSV — free',
};

export const APP_HREF = '/app';
